# Password-protected file scenario
scenario_id: "password_protected_large_file_002"
source_apps: ["Outlook", "ExcelPreviewer", "ExcelDesktop"]
file_size_bucket: "large"
protection_level: "password"
file_type: "xlsx"
notes: "Large password-protected file should prompt for password before opening."





