# Example YAML config file for video analysis
scenario_id: "outlook_preview_to_excel_001"
source_apps: 
  - "Outlook"
  - "ExcelPreviewer" 
  - "ExcelDesktop"
file_size_bucket: "medium"        # small|medium|large
protection_level: "confidential"  # none|password|confidential|highly_confidential
file_type: "xlsx"
notes: "Open attachment in Previewer → Open in Desktop → edit."

